"""
extractors/registry.py
──────────────────────
Registro centralizado de TODAS las funciones extractoras.
Cada entrada tiene:
  - name:        nombre único (el que el LLM referencia)
  - func:        callable(json_data, ...) -> dict
  - args:        número de argumentos ADICIONALES al json_data (0 o 1)
  - description: texto corto para el prompt del planner
  - keywords:    lista de palabras clave para el router determinístico
  - section:     sección principal del JSON a la que pertenece
"""
from typing import Any, Callable, Dict, List

# ─────── Importaciones de extractores ───────
from extractors.cabecera_legajo import (
    obtener_cabecera_legajo,
    obtener_clave, obtener_ide, obtener_orden_sufijo,
    obtener_organismo_codigo, obtener_organismo_descripcion,
    obtener_tipo_expediente, obtener_numero_expediente, obtener_anio_expediente,
    obtener_estado_expediente_codigo, obtener_estado_expediente_descripcion,
    obtener_fecha_registro, obtener_nivel_acceso,
    obtener_caratula_publica, obtener_caratula_privada,
    obtener_fecha_inicio, obtener_fecha_modificacion,
    obtener_usuario_alta, obtener_usuario_baja, obtener_usuario_modificacion,
    obtener_dependencia_radicacion_codigo, obtener_dependencia_radicacion_descripcion,
    obtener_tipo_proceso, obtener_etapa_procesal_codigo, obtener_etapa_procesal_descripcion,
    obtener_prioridad, obtener_cuij, obtener_materias_cabecera,
    obtener_ubicacion_actual_codigo, obtener_ubicacion_actual_descripcion,
    obtener_secretaria_codigo, obtener_secretaria_descripcion,
)
from extractors.personas_legajo import (
    listar_personas,
    buscar_persona_por_nombre, buscar_persona_por_dni, buscar_persona_por_cuil,
    buscar_persona_por_tipo_documento, buscar_persona_por_fecha_nacimiento,
    buscar_persona_por_genero, buscar_persona_por_rol,
    buscar_persona_por_estado_detencion,
    buscar_persona_por_fecha_desde, buscar_persona_por_fecha_hasta,
    listar_vinculos_personas, buscar_persona_por_codigo_vinculo,
    buscar_persona_por_descripcion_vinculo,
    listar_caracteristicas_personas,
    buscar_persona_por_caracteristica_genero, buscar_persona_por_es_menor,
    buscar_persona_por_ocupacion, buscar_persona_por_estado_civil,
    buscar_persona_por_nivel_educativo, buscar_persona_por_lugar_nacimiento,
    listar_calificaciones_legales_personas,
    listar_relacionados_personas, buscar_relacionado_por_nombre,
    buscar_relacionado_por_tipo, buscar_relacionado_por_rol,
    listar_abogados_de_personas,
    listar_domicilios_relacionados,
    listar_domicilios_personas, buscar_domicilio_persona_por_clase,
    buscar_domicilio_persona_por_tipo,
    buscar_domicilio_persona_por_relacion_vinculo,
)
from extractors.abogados_legajo import (
    listar_abogados,
    buscar_abogado_por_nombre, buscar_abogado_por_dni, buscar_abogado_por_cuil,
    buscar_abogado_por_matricula, buscar_abogado_por_vinculo_codigo,
    buscar_abogado_por_vinculo_descripcion,
    buscar_abogado_por_fecha_nacimiento,
    buscar_abogado_por_fecha_desde, buscar_abogado_por_fecha_hasta,
    listar_representados, buscar_representado_por_nombre, buscar_representado_por_rol,
    buscar_abogados_de_cliente,
    listar_domicilios_representados,
    listar_domicilios_abogados, buscar_domicilio_abogado_por_clase,
    buscar_domicilio_abogado_por_tipo,
)
from extractors.funcionarios import (
    listar_funcionarios,
    buscar_funcionario_por_nombre, buscar_funcionario_por_dni,
    buscar_funcionario_por_cuil, buscar_funcionario_por_cargo,
    buscar_funcionario_por_fecha_desde, buscar_funcionario_por_fecha_hasta,
    listar_domicilios_funcionarios, buscar_domicilio_funcionario_por_email,
)
from extractors.causa import (
    obtener_causa, obtener_causa_descripcion, obtener_causa_fecha_hecho,
    obtener_causa_forma_inicio, obtener_causa_nivel_acceso,
    obtener_causa_caratula_publica, obtener_causa_caratula_privada,
)
from extractors.dependencias_vistas import (
    listar_dependencias,
    buscar_dependencia_por_organismo_codigo, buscar_dependencia_por_organismo_descripcion,
    buscar_dependencia_por_codigo, buscar_dependencia_por_descripcion,
    buscar_dependencia_por_clase_codigo, buscar_dependencia_por_clase_descripcion,
    buscar_dependencia_por_jerarquia, buscar_dependencia_por_rol,
    buscar_dependencia_por_activo,
    buscar_dependencia_por_fecha_desde, buscar_dependencia_por_fecha_hasta,
    listar_tipos_dependencias, buscar_dependencia_por_tipo_codigo,
    buscar_dependencia_por_tipo_descripcion,
)
from extractors.radicaciones import (
    listar_radicaciones,
    buscar_radicacion_por_organismo_codigo, buscar_radicacion_por_organismo_descripcion,
    buscar_radicacion_por_motivo_codigo, buscar_radicacion_por_motivo_descripcion,
    buscar_radicacion_por_fecha_desde, buscar_radicacion_por_fecha_hasta,
)
from extractors.materia_delitos import (
    listar_delitos,
    buscar_delito_por_codigo, buscar_delito_por_descripcion, buscar_delito_por_orden,
)
from extractors.extras import (
    listar_clasificadores_legajo, buscar_clasificador_por_descripcion,
    obtener_organismo_control, obtener_organismo_control_codigo,
    obtener_organismo_control_descripcion,
    obtener_clave_causa, obtener_codigo_sistema, obtener_codigo_entidad,
    obtener_estado_legajo, obtener_seguridad,
)


# ═══════════════════════════════════════════════════════════════
#  Tipo de entrada del registro
# ═══════════════════════════════════════════════════════════════

class ToolEntry:
    __slots__ = ("name", "func", "args", "description", "keywords", "section")

    def __init__(self, name: str, func: Callable, args: int,
                 description: str, keywords: List[str], section: str):
        self.name = name
        self.func = func
        self.args = args  # 0 = solo json_data, 1 = json_data + 1 argumento
        self.description = description
        self.keywords = keywords
        self.section = section


# ═══════════════════════════════════════════════════════════════
#  Registro completo
# ═══════════════════════════════════════════════════════════════

TOOL_REGISTRY: List[ToolEntry] = [
    # ──────── CABECERA_LEGAJO ────────
    ToolEntry("obtener_cabecera_legajo", obtener_cabecera_legajo, 0,
              "Devuelve TODA la información general del expediente (cabecera completa).",
              ["expediente", "cabecera", "legajo", "informacion general", "datos generales"], "cabecera_legajo"),
    ToolEntry("obtener_clave", obtener_clave, 0,
              "Devuelve la clave identificadora del legajo.",
              ["clave", "clave legajo", "identificador"], "cabecera_legajo"),
    ToolEntry("obtener_ide", obtener_ide, 0,
              "Devuelve el IDE del legajo.",
              ["ide", "identificador expediente"], "cabecera_legajo"),
    ToolEntry("obtener_organismo_codigo", obtener_organismo_codigo, 0,
              "Devuelve el código del organismo que lleva el expediente.",
              ["organismo codigo", "codigo organismo"], "cabecera_legajo"),
    ToolEntry("obtener_organismo_descripcion", obtener_organismo_descripcion, 0,
              "Devuelve la descripción del organismo que lleva el expediente.",
              ["organismo descripcion", "nombre organismo", "organismo"], "cabecera_legajo"),
    ToolEntry("obtener_tipo_expediente", obtener_tipo_expediente, 0,
              "Devuelve el tipo de expediente (ej: LJUADO).",
              ["tipo expediente", "tipo legajo", "clase expediente"], "cabecera_legajo"),
    ToolEntry("obtener_numero_expediente", obtener_numero_expediente, 0,
              "Devuelve el número del expediente.",
              ["numero expediente", "nro expediente", "numero"], "cabecera_legajo"),
    ToolEntry("obtener_anio_expediente", obtener_anio_expediente, 0,
              "Devuelve el año del expediente.",
              ["anio expediente", "año expediente", "año", "anio"], "cabecera_legajo"),
    ToolEntry("obtener_estado_expediente_codigo", obtener_estado_expediente_codigo, 0,
              "Devuelve el código del estado del expediente (ej: INIT).",
              ["estado codigo", "estado expediente codigo"], "cabecera_legajo"),
    ToolEntry("obtener_estado_expediente_descripcion", obtener_estado_expediente_descripcion, 0,
              "Devuelve la descripción del estado del expediente (ej: Iniciado).",
              ["estado expediente", "estado", "estado descripcion"], "cabecera_legajo"),
    ToolEntry("obtener_fecha_registro", obtener_fecha_registro, 0,
              "Devuelve la fecha de registro del expediente.",
              ["fecha registro", "fecha alta", "registrado"], "cabecera_legajo"),
    ToolEntry("obtener_nivel_acceso", obtener_nivel_acceso, 0,
              "Devuelve el nivel de acceso del expediente (PÚBLICO, PRIVADO).",
              ["nivel acceso", "acceso", "publico privado", "visibilidad"], "cabecera_legajo"),
    ToolEntry("obtener_caratula_publica", obtener_caratula_publica, 0,
              "Devuelve la carátula pública del expediente.",
              ["caratula publica", "caratula"], "cabecera_legajo"),
    ToolEntry("obtener_caratula_privada", obtener_caratula_privada, 0,
              "Devuelve la carátula privada del expediente.",
              ["caratula privada"], "cabecera_legajo"),
    ToolEntry("obtener_fecha_inicio", obtener_fecha_inicio, 0,
              "Devuelve la fecha de inicio del proceso judicial.",
              ["fecha inicio", "inicio proceso", "cuando inicio", "cuando empezo"], "cabecera_legajo"),
    ToolEntry("obtener_fecha_modificacion", obtener_fecha_modificacion, 0,
              "Devuelve la fecha de la última modificación.",
              ["fecha modificacion", "ultima modificacion", "modificado"], "cabecera_legajo"),
    ToolEntry("obtener_usuario_alta", obtener_usuario_alta, 0,
              "Devuelve el usuario que dio de alta el expediente.",
              ["usuario alta", "quien creo", "creador"], "cabecera_legajo"),
    ToolEntry("obtener_usuario_baja", obtener_usuario_baja, 0,
              "Devuelve el usuario que dio de baja el expediente.",
              ["usuario baja"], "cabecera_legajo"),
    ToolEntry("obtener_usuario_modificacion", obtener_usuario_modificacion, 0,
              "Devuelve el usuario que realizó la última modificación.",
              ["usuario modificacion", "quien modifico"], "cabecera_legajo"),
    ToolEntry("obtener_dependencia_radicacion_codigo", obtener_dependencia_radicacion_codigo, 0,
              "Devuelve el código de la dependencia de radicación.",
              ["dependencia radicacion codigo"], "cabecera_legajo"),
    ToolEntry("obtener_dependencia_radicacion_descripcion", obtener_dependencia_radicacion_descripcion, 0,
              "Devuelve la descripción de la dependencia de radicación.",
              ["dependencia radicacion descripcion", "dependencia radicacion"], "cabecera_legajo"),
    ToolEntry("obtener_tipo_proceso", obtener_tipo_proceso, 0,
              "Devuelve el tipo de proceso (ej: Proceso Ordinario).",
              ["tipo proceso", "proceso ordinario", "proceso"], "cabecera_legajo"),
    ToolEntry("obtener_etapa_procesal_codigo", obtener_etapa_procesal_codigo, 0,
              "Devuelve el código de la etapa procesal.",
              ["etapa procesal codigo"], "cabecera_legajo"),
    ToolEntry("obtener_etapa_procesal_descripcion", obtener_etapa_procesal_descripcion, 0,
              "Devuelve la descripción de la etapa procesal (ej: Preparatoria).",
              ["etapa procesal", "etapa", "fase procesal"], "cabecera_legajo"),
    ToolEntry("obtener_prioridad", obtener_prioridad, 0,
              "Devuelve la prioridad del expediente (ALTA, MODERADO, BAJA).",
              ["prioridad", "urgencia", "prioridad expediente"], "cabecera_legajo"),
    ToolEntry("obtener_cuij", obtener_cuij, 0,
              "Devuelve el CUIJ (código único de identificación judicial).",
              ["cuij", "codigo unico", "identificacion judicial"], "cabecera_legajo"),
    ToolEntry("obtener_materias_cabecera", obtener_materias_cabecera, 0,
              "Devuelve las materias jurídicas del expediente.",
              ["materias", "materia expediente", "materia juridica"], "cabecera_legajo"),
    ToolEntry("obtener_ubicacion_actual_codigo", obtener_ubicacion_actual_codigo, 0,
              "Devuelve el código de la ubicación actual del expediente.",
              ["ubicacion actual codigo", "donde esta"], "cabecera_legajo"),
    ToolEntry("obtener_ubicacion_actual_descripcion", obtener_ubicacion_actual_descripcion, 0,
              "Devuelve la descripción de la ubicación actual.",
              ["ubicacion actual", "ubicacion", "donde se encuentra"], "cabecera_legajo"),
    ToolEntry("obtener_secretaria_codigo", obtener_secretaria_codigo, 0,
              "Devuelve el código de la secretaría.",
              ["secretaria codigo"], "cabecera_legajo"),
    ToolEntry("obtener_secretaria_descripcion", obtener_secretaria_descripcion, 0,
              "Devuelve la descripción de la secretaría.",
              ["secretaria", "secretaria descripcion"], "cabecera_legajo"),

    # ──────── PERSONAS_LEGAJO ────────
    ToolEntry("listar_personas", listar_personas, 0,
              "Devuelve TODAS las personas involucradas en el legajo.",
              ["todas las personas", "listar personas", "personas legajo", "personas involucradas", "quienes participan"], "personas_legajo"),
    ToolEntry("buscar_persona_por_nombre", buscar_persona_por_nombre, 1,
              "Busca una persona por nombre, apellido o nombre completo. Argumento: nombre.",
              ["persona nombre", "buscar persona", "quien es"], "personas_legajo"),
    ToolEntry("buscar_persona_por_dni", buscar_persona_por_dni, 1,
              "Busca persona por número de DNI. Argumento: numero_documento.",
              ["persona dni", "documento", "dni"], "personas_legajo"),
    ToolEntry("buscar_persona_por_cuil", buscar_persona_por_cuil, 1,
              "Busca persona por CUIL. Argumento: cuil.",
              ["persona cuil", "cuil"], "personas_legajo"),
    ToolEntry("buscar_persona_por_tipo_documento", buscar_persona_por_tipo_documento, 1,
              "Filtra personas por tipo de documento (DNI, Pasaporte). Argumento: tipo.",
              ["tipo documento persona"], "personas_legajo"),
    ToolEntry("buscar_persona_por_fecha_nacimiento", buscar_persona_por_fecha_nacimiento, 1,
              "Busca persona por fecha de nacimiento (AAAA-MM-DD). Argumento: fecha.",
              ["fecha nacimiento persona", "nacimiento persona", "cuando nacio"], "personas_legajo"),
    ToolEntry("buscar_persona_por_genero", buscar_persona_por_genero, 1,
              "Filtra personas por género. Argumento: genero.",
              ["genero persona", "sexo persona"], "personas_legajo"),
    ToolEntry("buscar_persona_por_rol", buscar_persona_por_rol, 1,
              "Filtra personas por rol (imputado, victima, actor, demandado). Argumento: rol.",
              ["persona rol", "imputado", "victima", "actor", "demandado", "rol persona"], "personas_legajo"),
    ToolEntry("buscar_persona_por_estado_detencion", buscar_persona_por_estado_detencion, 1,
              "Filtra personas detenidas o no. Argumento: true/false.",
              ["detenido", "detencion", "persona detenida", "esta detenido", "preso"], "personas_legajo"),
    ToolEntry("buscar_persona_por_fecha_desde", buscar_persona_por_fecha_desde, 1,
              "Busca personas por fecha_desde de participación. Argumento: fecha.",
              ["persona fecha desde", "participacion desde"], "personas_legajo"),
    ToolEntry("buscar_persona_por_fecha_hasta", buscar_persona_por_fecha_hasta, 1,
              "Busca personas por fecha_hasta de participación. Argumento: fecha.",
              ["persona fecha hasta", "participacion hasta"], "personas_legajo"),

    # ── Personas → vinculos ──
    ToolEntry("listar_vinculos_personas", listar_vinculos_personas, 0,
              "Devuelve los vínculos de todas las personas.",
              ["vinculos personas", "listar vinculos", "vinculaciones"], "personas_legajo"),
    ToolEntry("buscar_persona_por_codigo_vinculo", buscar_persona_por_codigo_vinculo, 1,
              "Busca personas por código de vínculo (IMP, VIC, ACT). Argumento: codigo.",
              ["codigo vinculo persona", "vinculo codigo"], "personas_legajo"),
    ToolEntry("buscar_persona_por_descripcion_vinculo", buscar_persona_por_descripcion_vinculo, 1,
              "Busca personas por descripción de vínculo (imputado, victima). Argumento: descripcion.",
              ["descripcion vinculo persona", "vinculo descripcion"], "personas_legajo"),

    # ── Personas → caracteristicas ──
    ToolEntry("listar_caracteristicas_personas", listar_caracteristicas_personas, 0,
              "Devuelve las características de todas las personas (género, menor, ocupación, etc.).",
              ["caracteristicas personas", "datos personales"], "personas_legajo"),
    ToolEntry("buscar_persona_por_caracteristica_genero", buscar_persona_por_caracteristica_genero, 1,
              "Filtra por género en características (MASCULINO, FEMENINO). Argumento: genero.",
              ["genero caracteristica", "caracteristica genero"], "personas_legajo"),
    ToolEntry("buscar_persona_por_es_menor", buscar_persona_por_es_menor, 1,
              "Filtra personas menores de edad. Argumento: true/false.",
              ["menor edad", "es menor", "menores"], "personas_legajo"),
    ToolEntry("buscar_persona_por_ocupacion", buscar_persona_por_ocupacion, 1,
              "Filtra personas por ocupación. Argumento: ocupacion.",
              ["ocupacion persona", "trabajo persona", "profesion"], "personas_legajo"),
    ToolEntry("buscar_persona_por_estado_civil", buscar_persona_por_estado_civil, 1,
              "Filtra personas por estado civil. Argumento: estado.",
              ["estado civil persona", "casado", "soltero"], "personas_legajo"),
    ToolEntry("buscar_persona_por_nivel_educativo", buscar_persona_por_nivel_educativo, 1,
              "Filtra personas por nivel educativo. Argumento: nivel.",
              ["nivel educativo", "educacion persona", "estudios"], "personas_legajo"),
    ToolEntry("buscar_persona_por_lugar_nacimiento", buscar_persona_por_lugar_nacimiento, 1,
              "Filtra personas por lugar de nacimiento. Argumento: lugar.",
              ["lugar nacimiento", "donde nacio", "nacido en"], "personas_legajo"),

    # ── Personas → calificaciones_legales ──
    ToolEntry("listar_calificaciones_legales_personas", listar_calificaciones_legales_personas, 0,
              "Devuelve las calificaciones legales de las personas.",
              ["calificaciones legales", "calificacion legal"], "personas_legajo"),

    # ── Personas → relacionados ──
    ToolEntry("listar_relacionados_personas", listar_relacionados_personas, 0,
              "Devuelve los relacionados (abogados, representantes) de cada persona.",
              ["relacionados personas", "personas relacionadas", "representante legal"], "personas_legajo"),
    ToolEntry("buscar_relacionado_por_nombre", buscar_relacionado_por_nombre, 1,
              "Busca un relacionado por nombre. Argumento: nombre.",
              ["relacionado nombre", "buscar relacionado"], "personas_legajo"),
    ToolEntry("buscar_relacionado_por_tipo", buscar_relacionado_por_tipo, 1,
              "Filtra relacionados por tipo (persona, abogado). Argumento: tipo.",
              ["relacionado tipo", "tipo relacionado"], "personas_legajo"),
    ToolEntry("buscar_relacionado_por_rol", buscar_relacionado_por_rol, 1,
              "Filtra relacionados por rol. Argumento: rol.",
              ["relacionado rol", "rol relacionado", "representante legal no letrado"], "personas_legajo"),
    ToolEntry("listar_abogados_de_personas", listar_abogados_de_personas, 0,
              "Extrae los abogados/defensores embebidos en personas_legajo[].relacionados. "
              "Usar con depends_on para obtener los defensores de personas ya filtradas (ej: imputados). "
              "NO busca en abogados_legajo, sino en los relacionados de cada persona.",
              ["defensor de persona", "abogado de imputado", "quien defiende", "quien representa a la persona",
               "abogado del imputado", "defensor del imputado", "abogado de la victima",
               "quien es el abogado", "abogados de personas"], "personas_legajo"),

    # ── Personas → relacionados → domicilios ──
    ToolEntry("listar_domicilios_relacionados", listar_domicilios_relacionados, 0,
              "Devuelve los domicilios de los relacionados de personas.",
              ["domicilios relacionados", "direccion relacionado"], "personas_legajo"),

    # ── Personas → domicilios ──
    ToolEntry("listar_domicilios_personas", listar_domicilios_personas, 0,
              "Devuelve los domicilios de las personas.",
              ["domicilios personas", "direccion persona", "telefono persona", "contacto persona"], "personas_legajo"),
    ToolEntry("buscar_domicilio_persona_por_clase", buscar_domicilio_persona_por_clase, 1,
              "Filtra domicilios de persona por clase (FISICO, ELECTRONICO). Argumento: clase.",
              ["clase domicilio persona", "domicilio fisico persona", "domicilio electronico persona"], "personas_legajo"),
    ToolEntry("buscar_domicilio_persona_por_tipo", buscar_domicilio_persona_por_tipo, 1,
              "Busca domicilios de persona buscando el argumento en TODOS los campos del domicilio "
              "(clase, digital_clase, digital_clase_codigo, empresa, relacion_vinculo, descripcion, etc.). "
              "Usar cuando se pide el celular, teléfono, email, o cualquier dato de contacto de personas. "
              "Argumento: valor a buscar (ej: 'celular', 'CEL', 'email', 'ELECTRONICO').",
              ["celular persona", "telefono persona", "email persona", "tipo contacto persona",
               "numero celular persona", "numero telefono persona"], "personas_legajo"),
    ToolEntry("buscar_domicilio_persona_por_relacion_vinculo", buscar_domicilio_persona_por_relacion_vinculo, 1,
              "Filtra domicilios por relación del vínculo (PROPIO, HERMANO, TIO). Argumento: relacion.",
              ["relacion vinculo domicilio", "domicilio propio", "domicilio hermano"], "personas_legajo"),

    # ──────── ABOGADOS_LEGAJO ────────
    ToolEntry("listar_abogados", listar_abogados, 0,
              "Devuelve TODOS los abogados del legajo.",
              ["todos los abogados", "listar abogados", "abogados legajo"], "abogados_legajo"),
    ToolEntry("buscar_abogado_por_nombre", buscar_abogado_por_nombre, 1,
              "Busca un abogado por nombre. Argumento: nombre.",
              ["abogado nombre", "buscar abogado", "nombre abogado"], "abogados_legajo"),
    ToolEntry("buscar_abogado_por_dni", buscar_abogado_por_dni, 1,
              "Busca abogado por DNI. Argumento: dni.",
              ["abogado dni", "dni abogado", "documento abogado"], "abogados_legajo"),
    ToolEntry("buscar_abogado_por_cuil", buscar_abogado_por_cuil, 1,
              "Busca abogado por CUIL. Argumento: cuil.",
              ["abogado cuil", "cuil abogado"], "abogados_legajo"),
    ToolEntry("buscar_abogado_por_matricula", buscar_abogado_por_matricula, 1,
              "Busca abogado por matrícula. Argumento: matricula.",
              ["matricula abogado", "numero matricula", "matricula"], "abogados_legajo"),
    ToolEntry("buscar_abogado_por_vinculo_codigo", buscar_abogado_por_vinculo_codigo, 1,
              "Filtra abogados por código de vínculo (DPUB, DPRIV). Argumento: codigo.",
              ["vinculo codigo abogado", "defensor publico codigo", "defensor privado codigo"], "abogados_legajo"),
    ToolEntry("buscar_abogado_por_vinculo_descripcion", buscar_abogado_por_vinculo_descripcion, 1,
              "Filtra abogados por descripción de vínculo (defensor publico, defensor privado). Argumento: desc.",
              ["vinculo descripcion abogado", "defensor publico", "defensor privado", "tipo abogado"], "abogados_legajo"),
    ToolEntry("buscar_abogado_por_fecha_nacimiento", buscar_abogado_por_fecha_nacimiento, 1,
              "Busca abogado por fecha de nacimiento. Argumento: fecha.",
              ["fecha nacimiento abogado", "nacimiento abogado"], "abogados_legajo"),
    ToolEntry("buscar_abogado_por_fecha_desde", buscar_abogado_por_fecha_desde, 1,
              "Filtra abogados por fecha_desde. Argumento: fecha.",
              ["abogado fecha desde"], "abogados_legajo"),
    ToolEntry("buscar_abogado_por_fecha_hasta", buscar_abogado_por_fecha_hasta, 1,
              "Filtra abogados por fecha_hasta. Argumento: fecha.",
              ["abogado fecha hasta"], "abogados_legajo"),

    # ── Abogados → representados ──
    ToolEntry("listar_representados", listar_representados, 0,
              "Devuelve todos los representados de cada abogado.",
              ["representados", "clientes abogado", "a quien representa", "representados abogados"], "abogados_legajo"),
    ToolEntry("buscar_representado_por_nombre", buscar_representado_por_nombre, 1,
              "Busca representados por nombre. Argumento: nombre.",
              ["representado nombre", "cliente nombre"], "abogados_legajo"),
    ToolEntry("buscar_representado_por_rol", buscar_representado_por_rol, 1,
              "Filtra representados por rol. Argumento: rol.",
              ["representado rol", "cliente rol"], "abogados_legajo"),
    ToolEntry("buscar_abogados_de_cliente", buscar_abogados_de_cliente, 1,
              "Dado un nombre de cliente/persona, devuelve sus abogados. Argumento: nombre_cliente.",
              ["abogados de cliente", "quien representa a", "abogado de"], "abogados_legajo"),

    # ── Abogados → representados → domicilios ──
    ToolEntry("listar_domicilios_representados", listar_domicilios_representados, 0,
              "Devuelve los domicilios de los representados.",
              ["domicilios representados", "direccion representado"], "abogados_legajo"),

    # ── Abogados → domicilios ──
    ToolEntry("listar_domicilios_abogados", listar_domicilios_abogados, 0,
              "Devuelve los domicilios de los abogados.",
              ["domicilios abogados", "direccion abogado", "contacto abogado"], "abogados_legajo"),
    ToolEntry("buscar_domicilio_abogado_por_clase", buscar_domicilio_abogado_por_clase, 1,
              "Filtra domicilios de abogado por clase (FISICO, ELECTRONICO). Argumento: clase.",
              ["clase domicilio abogado"], "abogados_legajo"),
    ToolEntry("buscar_domicilio_abogado_por_tipo", buscar_domicilio_abogado_por_tipo, 1,
              "Busca domicilios de abogado buscando el argumento en TODOS los campos del domicilio "
              "(clase, digital_clase, digital_clase_codigo, empresa, relacion_vinculo, descripcion, etc.). "
              "Usar cuando se pide el celular, teléfono, email, o cualquier dato de contacto de abogados. "
              "Argumento: valor a buscar (ej: 'celular', 'CEL', 'email', 'ELECTRONICO').",
              ["celular abogado", "telefono abogado", "email abogado", "tipo contacto abogado",
               "numero celular abogado", "numero telefono abogado"], "abogados_legajo"),

    # ──────── FUNCIONARIOS ────────
    ToolEntry("listar_funcionarios", listar_funcionarios, 0,
              "Devuelve TODOS los funcionarios del legajo.",
              ["todos los funcionarios", "listar funcionarios", "funcionarios"], "funcionarios"),
    ToolEntry("buscar_funcionario_por_nombre", buscar_funcionario_por_nombre, 1,
              "Busca funcionario por nombre. Argumento: nombre.",
              ["funcionario nombre", "buscar funcionario", "nombre funcionario"], "funcionarios"),
    ToolEntry("buscar_funcionario_por_dni", buscar_funcionario_por_dni, 1,
              "Busca funcionario por DNI. Argumento: dni.",
              ["funcionario dni", "dni funcionario"], "funcionarios"),
    ToolEntry("buscar_funcionario_por_cuil", buscar_funcionario_por_cuil, 1,
              "Busca funcionario por CUIL. Argumento: cuil.",
              ["funcionario cuil", "cuil funcionario"], "funcionarios"),
    ToolEntry("buscar_funcionario_por_cargo", buscar_funcionario_por_cargo, 1,
              "Busca funcionario por cargo (fiscal, juez, etc.). Argumento: cargo.",
              ["cargo funcionario", "fiscal", "juez", "secretario", "cargo"], "funcionarios"),
    ToolEntry("buscar_funcionario_por_fecha_desde", buscar_funcionario_por_fecha_desde, 1,
              "Filtra funcionarios por fecha_desde. Argumento: fecha.",
              ["funcionario fecha desde"], "funcionarios"),
    ToolEntry("buscar_funcionario_por_fecha_hasta", buscar_funcionario_por_fecha_hasta, 1,
              "Filtra funcionarios por fecha_hasta. Argumento: fecha.",
              ["funcionario fecha hasta"], "funcionarios"),
    ToolEntry("listar_domicilios_funcionarios", listar_domicilios_funcionarios, 0,
              "Devuelve los domicilios/emails de los funcionarios.",
              ["domicilios funcionarios", "email funcionario", "contacto funcionario"], "funcionarios"),
    ToolEntry("buscar_domicilio_funcionario_por_email", buscar_domicilio_funcionario_por_email, 1,
              "Busca funcionario por email. Argumento: email.",
              ["email funcionario", "correo funcionario"], "funcionarios"),

    # ──────── CAUSA ────────
    ToolEntry("obtener_causa", obtener_causa, 0,
              "Devuelve TODA la información de la causa.",
              ["causa", "toda la causa", "informacion causa", "datos causa"], "causa"),
    ToolEntry("obtener_causa_descripcion", obtener_causa_descripcion, 0,
              "Devuelve la descripción de la causa.",
              ["descripcion causa", "de que se trata la causa"], "causa"),
    ToolEntry("obtener_causa_fecha_hecho", obtener_causa_fecha_hecho, 0,
              "Devuelve la fecha del hecho de la causa.",
              ["fecha hecho", "cuando ocurrio", "cuando fue el hecho", "fecha causa"], "causa"),
    ToolEntry("obtener_causa_forma_inicio", obtener_causa_forma_inicio, 0,
              "Devuelve la forma de inicio de la causa (EN POLICIA, etc.).",
              ["forma inicio", "como inicio", "como empezo la causa", "origen causa"], "causa"),
    ToolEntry("obtener_causa_nivel_acceso", obtener_causa_nivel_acceso, 0,
              "Devuelve el nivel de acceso de la causa.",
              ["nivel acceso causa"], "causa"),
    ToolEntry("obtener_causa_caratula_publica", obtener_causa_caratula_publica, 0,
              "Devuelve la carátula pública de la causa.",
              ["caratula publica causa"], "causa"),
    ToolEntry("obtener_causa_caratula_privada", obtener_causa_caratula_privada, 0,
              "Devuelve la carátula privada de la causa.",
              ["caratula privada causa"], "causa"),

    # ──────── DEPENDENCIAS_VISTAS ────────
    ToolEntry("listar_dependencias", listar_dependencias, 0,
              "Devuelve TODAS las dependencias vistas.",
              ["todas las dependencias", "listar dependencias", "dependencias vistas", "organismos dependencias"], "dependencias_vistas"),
    ToolEntry("buscar_dependencia_por_organismo_codigo", buscar_dependencia_por_organismo_codigo, 1,
              "Filtra dependencias por código de organismo. Argumento: codigo.",
              ["organismo codigo dependencia"], "dependencias_vistas"),
    ToolEntry("buscar_dependencia_por_organismo_descripcion", buscar_dependencia_por_organismo_descripcion, 1,
              "Filtra dependencias por descripción de organismo. Argumento: desc.",
              ["organismo descripcion dependencia"], "dependencias_vistas"),
    ToolEntry("buscar_dependencia_por_codigo", buscar_dependencia_por_codigo, 1,
              "Filtra dependencias por código. Argumento: codigo.",
              ["dependencia codigo", "codigo dependencia"], "dependencias_vistas"),
    ToolEntry("buscar_dependencia_por_descripcion", buscar_dependencia_por_descripcion, 1,
              "Filtra dependencias por descripción. Argumento: desc.",
              ["dependencia descripcion", "buscar dependencia"], "dependencias_vistas"),
    ToolEntry("buscar_dependencia_por_clase_codigo", buscar_dependencia_por_clase_codigo, 1,
              "Filtra dependencias por código de clase. Argumento: codigo.",
              ["clase codigo dependencia"], "dependencias_vistas"),
    ToolEntry("buscar_dependencia_por_clase_descripcion", buscar_dependencia_por_clase_descripcion, 1,
              "Filtra dependencias por descripción de clase. Argumento: desc.",
              ["clase descripcion dependencia"], "dependencias_vistas"),
    ToolEntry("buscar_dependencia_por_jerarquia", buscar_dependencia_por_jerarquia, 1,
              "Filtra dependencias por jerarquía. Argumento: jerarquia.",
              ["jerarquia dependencia"], "dependencias_vistas"),
    ToolEntry("buscar_dependencia_por_rol", buscar_dependencia_por_rol, 1,
              "Filtra dependencias por rol (LEGAJO_OWNER, INGRESO). Argumento: rol.",
              ["rol dependencia", "dependencia rol"], "dependencias_vistas"),
    ToolEntry("buscar_dependencia_por_activo", buscar_dependencia_por_activo, 1,
              "Filtra dependencias activas o inactivas. Argumento: true/false.",
              ["dependencia activa", "activo dependencia"], "dependencias_vistas"),
    ToolEntry("buscar_dependencia_por_fecha_desde", buscar_dependencia_por_fecha_desde, 1,
              "Filtra dependencias por fecha_desde. Argumento: fecha.",
              ["dependencia fecha desde"], "dependencias_vistas"),
    ToolEntry("buscar_dependencia_por_fecha_hasta", buscar_dependencia_por_fecha_hasta, 1,
              "Filtra dependencias por fecha_hasta. Argumento: fecha.",
              ["dependencia fecha hasta"], "dependencias_vistas"),

    # ── Dependencias → tipos ──
    ToolEntry("listar_tipos_dependencias", listar_tipos_dependencias, 0,
              "Devuelve los tipos de cada dependencia.",
              ["tipos dependencias", "tipos de dependencias"], "dependencias_vistas"),
    ToolEntry("buscar_dependencia_por_tipo_codigo", buscar_dependencia_por_tipo_codigo, 1,
              "Filtra dependencias por código de tipo. Argumento: tipo_codigo.",
              ["tipo codigo dependencia"], "dependencias_vistas"),
    ToolEntry("buscar_dependencia_por_tipo_descripcion", buscar_dependencia_por_tipo_descripcion, 1,
              "Filtra dependencias por descripción de tipo. Argumento: tipo_desc.",
              ["tipo descripcion dependencia"], "dependencias_vistas"),

    # ──────── RADICACIONES ────────
    ToolEntry("listar_radicaciones", listar_radicaciones, 0,
              "Devuelve TODAS las radicaciones y movimientos del expediente.",
              ["todas las radicaciones", "listar radicaciones", "radicaciones", "movimientos expediente"], "radicaciones"),
    ToolEntry("buscar_radicacion_por_organismo_codigo", buscar_radicacion_por_organismo_codigo, 1,
              "Filtra radicaciones por código de organismo. Argumento: codigo.",
              ["organismo codigo radicacion"], "radicaciones"),
    ToolEntry("buscar_radicacion_por_organismo_descripcion", buscar_radicacion_por_organismo_descripcion, 1,
              "Filtra radicaciones por descripción de organismo. Argumento: desc.",
              ["organismo descripcion radicacion"], "radicaciones"),
    ToolEntry("buscar_radicacion_por_motivo_codigo", buscar_radicacion_por_motivo_codigo, 1,
              "Filtra radicaciones por código de motivo. Argumento: codigo.",
              ["motivo codigo radicacion"], "radicaciones"),
    ToolEntry("buscar_radicacion_por_motivo_descripcion", buscar_radicacion_por_motivo_descripcion, 1,
              "Filtra radicaciones por descripción de motivo. Argumento: desc.",
              ["motivo descripcion radicacion", "motivo radicacion"], "radicaciones"),
    ToolEntry("buscar_radicacion_por_fecha_desde", buscar_radicacion_por_fecha_desde, 1,
              "Filtra radicaciones por fecha_desde. Argumento: fecha.",
              ["radicacion fecha desde"], "radicaciones"),
    ToolEntry("buscar_radicacion_por_fecha_hasta", buscar_radicacion_por_fecha_hasta, 1,
              "Filtra radicaciones por fecha_hasta. Argumento: fecha.",
              ["radicacion fecha hasta"], "radicaciones"),

    # ──────── MATERIA_DELITOS ────────
    ToolEntry("listar_delitos", listar_delitos, 0,
              "Devuelve TODOS los delitos asociados al legajo.",
              ["todos los delitos", "listar delitos", "materia delitos", "delitos"], "materia_delitos"),
    ToolEntry("buscar_delito_por_codigo", buscar_delito_por_codigo, 1,
              "Busca delito por código. Argumento: codigo.",
              ["codigo delito", "delito codigo"], "materia_delitos"),
    ToolEntry("buscar_delito_por_descripcion", buscar_delito_por_descripcion, 1,
              "Busca delito por descripción. Argumento: desc.",
              ["descripcion delito", "buscar delito", "que delito"], "materia_delitos"),
    ToolEntry("buscar_delito_por_orden", buscar_delito_por_orden, 1,
              "Busca delito por orden. Argumento: orden.",
              ["orden delito"], "materia_delitos"),

    # ──────── EXTRAS ────────
    ToolEntry("listar_clasificadores_legajo", listar_clasificadores_legajo, 0,
              "Devuelve todos los clasificadores del legajo.",
              ["clasificadores", "clasificacion legajo", "categorias"], "extras"),
    ToolEntry("buscar_clasificador_por_descripcion", buscar_clasificador_por_descripcion, 1,
              "Busca clasificador por descripción. Argumento: desc.",
              ["buscar clasificador", "clasificador descripcion"], "extras"),
    ToolEntry("obtener_organismo_control", obtener_organismo_control, 0,
              "Devuelve el organismo de control del legajo.",
              ["organismo control", "quien controla"], "extras"),
    ToolEntry("obtener_organismo_control_codigo", obtener_organismo_control_codigo, 0,
              "Devuelve el código del organismo de control.",
              ["codigo organismo control"], "extras"),
    ToolEntry("obtener_organismo_control_descripcion", obtener_organismo_control_descripcion, 0,
              "Devuelve la descripción del organismo de control.",
              ["descripcion organismo control"], "extras"),
    ToolEntry("obtener_clave_causa", obtener_clave_causa, 0,
              "Devuelve la clave de la causa (clave_causa).",
              ["clave causa"], "extras"),
    ToolEntry("obtener_codigo_sistema", obtener_codigo_sistema, 0,
              "Devuelve el código del sistema (THEMIS, etc.).",
              ["codigo sistema", "sistema", "themis"], "extras"),
    ToolEntry("obtener_codigo_entidad", obtener_codigo_entidad, 0,
              "Devuelve el código de entidad (LEGAJO, etc.).",
              ["codigo entidad", "entidad"], "extras"),
    ToolEntry("obtener_estado_legajo", obtener_estado_legajo, 0,
              "Devuelve el estado del legajo (PROCESADO, etc.).",
              ["estado legajo", "legajo procesado"], "extras"),
    ToolEntry("obtener_seguridad", obtener_seguridad, 0,
              "Devuelve la información de seguridad del legajo.",
              ["seguridad", "permisos", "acceso seguridad"], "extras"),
]


# ─── Diccionarios auxiliares ───
TOOL_BY_NAME: Dict[str, ToolEntry] = {t.name: t for t in TOOL_REGISTRY}
TOOL_NAMES: List[str] = [t.name for t in TOOL_REGISTRY]
